# Use a base image with OpenJDK
FROM openjdk:17-jdk-slim

# Argument for the JAR file location
ARG JAR_FILE=target/*.jar

# Copy the JAR file to the Docker image
COPY ${JAR_FILE} /home/app/app.jar

# Command to run the Spring Boot application
ENTRYPOINT ["java", "-jar", "/home/app/app.jar"]
