apiVersion: v1
kind: Secret
metadata:
  name: oziva-secrets
  namespace: oziva-namespace
type: Opaque
data:
  username: cG9zdGdyZXM=    # base 64 encoding of username
  password: U2FuZ2l0YUAxOTcx # base 64 encoding of password